#!/bin/sh

# Author  : Fikri Rahmat Nurhidayat
# Mail    : fikrirnurhidayat@gmail.com
# Github  : @fikrirnurhidayat
# Twitter : @fikrirnurhidayat

rofi -no-lazy-grab -show window \
  -modi window \
  -theme "$HOME/.config/rofi/launcher/style.rasi"
