#!/bin/sh

git ls-files --others --exclude-standard | while read -r f; do
  realpath --relative-to="$(git rev-parse --show-toplevel)" "$f"
done >> "$(git rev-parse --show-toplevel)/.gitignore"

sort -u "$(git rev-parse --show-toplevel)/.gitignore" -o "$(git rev-parse --show-toplevel)/.gitignore"
