#!/bin/sh

options="Shutdown\nRestart\nSuspend"

choosen=$(echo -e "$options" | wofi --dmenu)

case $choosen in
    Shutdown)
        shutdown now
        ;;
    Restart)
        reboot
        ;;
    Suspend)
        systemctl suspend
        ;;
esac
