#!/bin/sh


options="screen\nrectangle\nwindow"

chosen="$(echo -e "$options" | wofi --dmenu)"

if [[ -f /usr/bin/grim ]]; then
  filename=$(date '+%F-%H-%M-%S').png
  screenshotdir="$(xdg-user-dir PICTURES)/Screenshots"
  mkdir -p $screenshotdir
  f="$screenshotdir/$filename"

  case $chosen in
      screen)
      sleep 1
      sh -c "grim - | tee $f | wl-copy" && dunstify --raw_icon="$f" "Screenshot captured!" "$filename"
          ;;
      rectangle)
          grim -g "$(slurp)" - | tee $f | wl-copy && dunstify --raw_icon="$f" "Screenshot captured!" "$filename"
          ;;
      window)
          GEOMETRY=$(swaymsg -t get_tree | jq -r '.. | select(.nodes? // empty) | .rect | "\(.x),\(.y) \(.width)x\(.height)"' | slurp)
          sh -c "grim -g '$GEOMETRY' - | tee $f | wl-copy" && dunstify --raw_icon="$f" "Screenshot captured!" "$filename"
          ;;
  esac
fi
