#!/bin/sh

# Define a function to get the property from a .desktop file
get_desktop_property() {
    file="$1"
    property="$2"
    grep "^$property=" "$file" | cut -d'=' -f2
}

# The directories containing your .desktop files
# You may want to update this to suit your needs
desktop_dirs="/usr/share/applications $HOME/.local/share/applications/"

# Initialize options for dmenu
options=""

# Loop over directories
for dir in $desktop_dirs; do
    # Use find to get .desktop files, read them line by line into a variable
    while IFS= read -r -d '' file
    do
        name=$(get_desktop_property "$file" "Name")
        # Only add to options if Name is non-empty
        if [ -n "$name" ]; then
            options="$options$name\n"
        fi
    done < <(find "$dir" -name '*.desktop' -print0)
done

# Remove the last newline
options=$(echo -e "$options" | sed '$d')

# Use dmenu to select a .desktop file
chosen=$(echo -e "$options" | dmenu -l 5 -i -p ' ')

# If user chose something, run the command
if [ -n "$chosen" ]; then
    # Get the corresponding .desktop file
    for dir in $desktop_dirs; do
        while IFS= read -r -d '' file
        do
            if grep -q "^Name=$chosen" "$file"; then
                chosen_file="$file"
                break
            fi
        done < <(find "$dir" -name '*.desktop' -print0)

        if [ -n "$chosen_file" ]; then
            break
        fi
    done

    # Get the command to execute
    exec=$(get_desktop_property "$chosen_file" "Exec")

    # Run the command
    if [ -n "$exec" ]; then
        sh -c "$exec" &
    fi
fi
