#!/bin/sh

options="shutdown\nrestart"

choosen="$(echo -e "$options" | dmenu -p "power " -vp 16 -c -l 3)"

case $choosen in
    shutdown)
        shutdown now
        ;;
    restart)
        reboot
        ;;
esac
