ANDROID_HOME="/opt/android-sdk"
ANDROID_SDK_ROOT="$ANDROID_HOME"
ANDROID_NDK="$ANDROID_HOME/ndk"
BROWSER=firefox
BUNDLE_PATH="$HOME/.local/share/ruby/gems"
DOTFILES="$HOME/.dotfiles"
EDITOR="nvim"
GOARCH="amd64"
GOPATH="$HOME/.local/share/go"
JAVA_HOME="/usr/lib/jvm/java-24-openjdk"
NODE_NO_WARNINGS=1
NODE_OPTIONS="--max-old-space-size=4096"
PATH="$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$PATH"
PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
PATH="$JAVA_HOME/bin:$PATH"
PATH="$PATH:$GOROOT/bin:$GOPATH/bin"
PATH="$PATH:$HOME/.cargo/bin"
PATH="$PATH:$HOME/.local/bin"
PATH="$PATH:$HOME/.local/share/scripts"
PATH="$PATH:$HOME/.npm/bin"
PATH="$PATH:$HOME/.rvm/bin"
PATH="$PATH:/opt/flutter/bin"
PATH="$PATH:/opt/pspdev/bin"
PATH="$PATH:$HOME/.local/share/gem/ruby/3.4.0/bin"
QT_STYLE_OVERRIDE=kvantum
TERMINAL="st"
VISUAL="nvim"
