preload = /usr/share/wallpapers/Next/contents/images_dark/1920x1080.png

wallpaper = eDP-1,/usr/share/wallpapers/Next/contents/images_dark/1920x1080.png
wallpaper = HDMI-A-1,/usr/share/wallpapers/Next/contents/images_dark/1920x1080.png