#!/bin/sh

# Editor stuff
alias edit="$EDITOR"
alias e="$EDITOR"

# Configuration stuff
alias conf-dotfiles="cd $DOTFILES && $EDITOR"

# Single file configuration
alias conf-picom="$EDITOR $DOTFILES/.config/picom.conf"
alias conf-aliases="$EDITOR $DOTFILES/.config/sh/aliases"
alias conf-environment="$EDITOR $DOTFILES/.config/environment"
alias conf-gtkrc-2.0="$EDITOR $DOTFILES/.gtkrc-2.0"
alias conf-kitty="$EDITOR $DOTFILES/.config/kitty/kitty.conf"

# Configure desktop shortcuts
alias conf-desktop="$EDITOR $HOME/.local/share/applications"

# Directory configuration
alias conf-dunst="cd $DOTFILES/.config/dunst && $EDITOR dunstrc"
alias conf-gtk-3.0="cd $DOTFILES/.config/gtk-3.0 && $EDITOR settings.ini"
