#!/bin/sh

# Editor stuff
alias vim="nvim"
alias v="nvim"

# Configuration stuff
alias conf-dotfiles="cd $DOTFILES && nvim"

# Single file configuration
alias conf-picom="nvim $DOTFILES/.config/picom.conf"
alias conf-aliases="nvim $DOTFILES/.config/sh/aliases"
alias conf-environment="nvim $DOTFILES/.config/environment"
alias conf-gtkrc-2.0="nvim $DOTFILES/.gtkrc-2.0"
alias conf-vimrc="nvim $DOTFILES/.vimrc"

# Directory configuration
alias conf-bspwm="cd $DOTFILES/.config/bspwm && nvim"
alias conf-nvim="cd $DOTFILES/.config/nvim && nvim"
alias conf-rofi="cd $DOTFILES/.config/polybar && nvim"
alias conf-kitty="cd $DOTFILES/.config/kitty && nvim"
alias conf-polybar="cd $DOTFILES/.config/polybar && nvim"
alias conf-dunst="cd $DOTFILES/.config/dunst && nvim"
alias conf-gtk-3.0="cd $DOTFILES/.config/gtk-3.0 && nvim"
alias conf-sxhkd="cd $DOTFILES/.config/sxhkd && nvim"
alias conf-vis="cd $DOTFILES/.config/vis && nvim"
