#!/bin/sh

# The next line updates PATH for the rvm
export PATH="$PATH:$HOME/.rvm/bin"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/fain/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/home/fain/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line updates PATH for the Yarn
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# The next lines set new variables for Golang
# also it updates PATH for golang binaries
export GOARCH="amd64"
export GOPATH="$HOME/Repositories/GO"
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

# Doom emacs
export PATH="$PATH:$HOME/.emacs.d/bin"

# Adds custom scripts and binaries
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.local/scripts"
export PATH="$PATH:$HOME/.scripts"

# Configuration stuff
export DOTFILES="$HOME/.dotfiles"
