#!/bin/sh

export EDITOR="emacsclient -nw -a ''"
export VISUAL="emacsclient -nc -a ''"
export TERMINAL="st"
export TOP="htop"

# The next line updates PATH for the rvm
export PATH="$PATH:$HOME/.rvm/bin"

# The next line updates PATH for the Yarn
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# The next lines set new variables for Golang
# also it updates PATH for golang binaries
export GOARCH="amd64"
export GOPATH="$HOME/.local/share/go"
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

# Rust
export PATH="$PATH:$HOME/.cargo/bin"

# Doom emacs
export PATH="$PATH:$HOME/.config/emacs/bin"

# Deno
export DENO_INSTALL="/home/fain/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"

# Adds custom scripts and binaries
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.local/scripts"
export PATH="$PATH:$HOME/.scripts"

# Android
export ANDROID_HOME="$HOME/.android/sdk"
export PATH="$PATH:$ANDROID_HOME/tools/bin"
export PATH="$PATH:$ANDROID_HOME/cmdline-tools/latest/bin"
export PATH="$PATH:$ANDROID_HOME/platform-tools"

# Flutter
export PATH="$PATH:$HOME/.pub-cache/bin"

# Configuration stuff
export DOTFILES="$HOME/.dotfiles"

# Flutter requires chome sadly.
export CHROME_EXECUTABLE="brave"

# Proton
export PATH="$PATH:$HOME/.steam/root/steamapps/common/Proton 7.0"

# GCP
export PATH="$PATH:$HOME/.local/share/google-cloud-sdk/bin"

# vkQuake
export PATH="$PATH:$HOME/Trashes/Repositories/vkQuake/build"
export PATH="$PATH:$HOME/.local/src/wal-telegram"
export PATH="$PATH:$HOME/.local/share/firefoxpwa/runtime"
