#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

"$HOME"/.config/polybar/bin/launch

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config window_gap           16
bspc config left_padding         16
bspc config right_padding        16
bspc config border_width         0

# bspc config normal_border_color "#3B4252"
# bspc config focused_border_color "#4C566A"

bspc config split_ratio          0.65
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Emacs desktop='^2'
bspc rule -a Brave desktop='^9'
bspc rule -a slack desktop='^10'
bspc rule -a TelegramDesktop desktop='^10'
bspc rule -a discord desktop='^10'
bspc rule -a Ardour-7.2.0 floating=on 
bspc rule -a steam desktop='^8'

bspc rule -a Emacs state=fullscreen
bspc rule -a kitty state=fullscreen

feh --bg-fill $HOME/Pictures/Wallpaper
