#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

"$HOME"/.config/polybar/bin/launch

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           32
bspc config left_padding         32
bspc config right_padding        32

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc rule -a Emacs desktop='^2'
bspc rule -a Brave desktop='^9'
bspc rule -a slack desktop='^10'
bspc rule -a TelegramDesktop desktop='^10'
bspc rule -a discord desktop='^10'

feh --bg-fill $HOME/Pictures/Wallpaper.png
