[General]

Background="Backgrounds/Wallpaper"
DimBackgroundImage="0.8"
ScaleImageCropped="true"
ScreenWidth="1920"
ScreenHeight="1080"
MainColor="{foreground}"
AccentColor="{color1}"
BackgroundColor="{background}"

## [Blur Settings]

FullBlur="true"
PartialBlur="false"
BlurRadius="16"

## [Design Customizations]

HaveFormBackground="false"
FormPosition="right"
BackgroundImageHAlignment="center"
BackgroundImageVAlignment="center"
OverrideLoginButtonTextColor=""
InterfaceShadowSize="6"
InterfaceShadowOpacity="1.0"
RoundCorners="20"
ScreenPadding="0"
Font="IBM Plex Sans"
FontSize=""

## [Interface Behavior]

ForceRightToLeft="false"
ForceLastUser="true"
ForcePasswordFocus="true"
ForceHideCompletePassword="true"
ForceHideVirtualKeyboardButton="false"
ForceHideSystemButtons="false"
AllowEmptyPassword="false"
AllowBadUsernames="false"

## [Locale Settings]

Locale=""
HourFormat="HH:mm"
DateFormat="dddd, d MMMM yyyy"

## [Translations]

HeaderText=""
TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateShowPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSession=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateVirtualKeyboardButton=""