#!/bin/sh

xrandr --output eDP1 --mode 1920x1080 --output HDMI1 --primary --mode 1920x1080 --rate 120 --left-of eDP1
bspc monitor HDMI1 -d 1 2 3 4 5 6 7 8 9
bspc monitor eDP1 -d 0

feh --bg-fill ~/Pictures/Wallpaper
