#!/bin/sh

walfile=$1

wal -i $walfile
pywalfox update
wal-telegram --wal

sed -i 's/#//g' "$HOME/.cache/wal/colors-foot"
cp $HOME/.config/foot/foot.template.ini $HOME/.config/foot/foot.ini
cat $HOME/.cache/wal/colors-foot >> $HOME/.config/foot/foot.ini

cp $walfile ~/Pictures/Wallpaper
cp $HOME/.cache/wal/dunstrc $HOME/.dotfiles/.config/dunst/dunstrc
cp $HOME/.cache/wal/colors-sway $HOME/.dotfiles/.config/sway/colors
cp $HOME/.cache/wal/colors-waybar.css $HOME/.dotfiles/.config/waybar/colors.css
cp $HOME/.cache/wal/colors-waybar.css $HOME/.dotfiles/.config/wofi/colors.css

if command -v mako > /dev/null 2>&1; then
    $HOME/.config/mako/update-theme.sh
fi

if command -v dunst >/dev/null 2>&1; then
    wal-dunst
    systemctl --user restart dunst
fi

sudo cp $walfile /usr/share/sddm/themes/sugar-candy/Backgrounds/Wallpaper
sudo cp $HOME/.cache/wal/sddm-theme.conf /usr/share/sddm/themes/sugar-candy/theme.conf 
