#+TITLE: Emacs Configuration
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el :tangle ~/.emacs.d/init.el
#+STARTUP: contents

Welcome to my emacs configuration. Take a look whatever you need.

* Package Management Setup

=use-package= will allow you to install package easily on various different source.

#+begin_src emacs-lisp
  (require 'package)

  (setq package-archives '(("melpa-stable" . "https://stable.melpa.org/packages/")
                           ("melpa" . "https://melpa.org/packages/")
                           ("org" . "https://orgmode.org/elpa/")
                           ("elpa" . "https://elpa.gnu.org/packages/")))

  (package-initialize)
  (unless package-archive-contents
    (package-refresh-contents))

  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  (require 'use-package)
  (setq use-package-always-ensure t)
#+end_src

* UI Configuration

We need to remove all unnecessary decoration on our emacs, to make it less noisy.

** Disable unnecessary decoration

Remove default decoration on emacs such as scroll bar, toolbar, etc.
- =inhibit-startup-message= is being used to inhibit the startup message, if the value is non-nil, it will inhibit the startup screen.
- =scroll-bar-mode= is a mode that will show the scrollbar on the emacs UI, by setting it into ~-1~ it will hide the scroll bar.
- =tool-bar-mode= is a mode that will show the toolbar on the emacs UI, by setting it into ~-1~ it will hide the toolbar.
- =menu-bar-mode= is a mode that will show the menubar on the emacs UI, by setting it into ~-1~ it will hide the menubar.
- =set-fringe-mode= I have no idea what is this.

#+begin_src emacs-lisp
  (setq inhibit-startup-message t)
  (scroll-bar-mode -1)            
  (tool-bar-mode -1)              
  (tooltip-mode -1)               
  (set-fringe-mode 10)            
  (menu-bar-mode -1)
#+end_src

** Global font configuration

There's three kind of face attribute on emacs that we can setup
- =default= face attribute
- =fixed-pitch= face attribute a.k.a ~Mono~ font
- =variable-pitch= face attribute a.k.a ~Variable Width~ font, being used on document like org-mode and manual.

#+begin_src emacs-lisp
  (set-face-attribute 'default nil :font "JetBrainsMono Nerd font:antialias=subpixel" :height 120)
  (set-face-attribute 'fixed-pitch nil :font "JetBrainsMono Nerd font:antialias=subpixel" :height 120)
  (set-face-attribute 'variable-pitch nil :font "JetBrainsMono Nerd font:antialias=subpixel" :height 120)
#+end_src

** Global UI configuration

Add more decoration that will improve our readability, such as line number and stuff.

#+begin_src emacs-lisp
  (column-number-mode)
  (global-display-line-numbers-mode t)
#+end_src

*** Disable line number on certain mode

#+begin_src emacs-lisp
  (dolist (mode '(org-mode-hook
                  term-mode-hook
                  shell-mode-hook
                  eshell-mode-hook
                  compilation-mode-hook))
    (add-hook mode (lambda () (display-line-numbers-mode 0))))
#+end_src

*** Add better modeline using =doom-modeline=

=all-the-icons= is being used for the icon that will be shown up inside modeline. The =doom-modeline= is basically just a better modeline for our emacs.

#+begin_src emacs-lisp
  (use-package all-the-icons)
  (use-package doom-modeline
    :ensure t
    :init (doom-modeline-mode 1)
    :custom ((doom-modeline-height 32)))
#+end_src

*** Theming

Install =doom-themes= we can easily install a lot of themes.

#+begin_src emacs-lisp
  (use-package doom-themes
    :ensure t
    :config
    (setq doom-themes-enable-bold t 
          doom-themes-enable-italic t)
    (load-theme 'doom-dracula t)
    (doom-themes-visual-bell-config)
    (doom-themes-neotree-config)
    (setq doom-themes-treemacs-theme "doom-colors")
    (doom-themes-treemacs-config)
    (doom-themes-org-config))
#+end_src

*** Language Specific

Add language specific styling such as =emacs-lisp=

#+begin_src emacs-lisp
  (use-package rainbow-delimiters
    :hook (prog-mode . rainbow-delimiters-mode))
#+end_src

** Prompt UI

By default our prompt doesn't display available properly, in fact it is hard to read, hence there's a package called =ivy= that will help you display proper prompt option. 

*** Ivy

=ivy= is package that we use to display available option as rows of option.

#+begin_src emacs-lisp
  (use-package ivy
    :diminish
    :bind (("C-s" . swiper)
           :map ivy-minibuffer-map
           ("C-l" . ivy-alt-done)
           ("C-j" . ivy-next-line)
           ("C-k" . ivy-previous-line)
           :map ivy-switch-buffer-map
           ("C-k" . ivy-previous-line)
           ("C-l" . ivy-done)
           ("C-d" . ivy-switch-buffer-kill)
           :map ivy-reverse-i-search-map
           ("C-k" . ivy-previous-line)
           ("C-d" . ivy-reverse-i-search-kill))
    :config
    (ivy-mode 1))
#+end_src

*** Counsel

=counsel= is basically just a package that can provide you information about the option that is available for you.

#+begin_src emacs-lisp
  (use-package counsel
    :bind (("M-x" . counsel-M-x)
           ("C-x b" . counsel-ibuffer)
           ("C-x C-f" . counsel-find-file)
           :map minibuffer-local-map
           ("C-r" . 'counsel-minibuffer-history)))
#+end_src

*** Which Keys

=which-key= package will help you to define what next keystoke that you might want to press.

#+begin_src emacs-lisp
  (use-package which-key
    :init (which-key-mode)
    :diminish which-key-mode
    :config
    (setq which-key-idle-delay 1))
#+end_src

* Development

There are bunch of package that will make our development process easier, so let's make me dependent to that package.

** Projectile

=projectile= is project buffer management
- You can find project by name
- You can find a file inside a project
- You can setup =test= script to run the test inside your project
- [[https://docs.projectile.mx/projectile/index.html][and more.]]

=projectile= has a variable called =projectile-project-search-path= which tells where the projectile find the project directory or files. So you'd better set this to your own directory path.

#+begin_src emacs-lisp
  (use-package projectile
    :diminish projectile-mode
    :config (projectile-mode)
    :custom ((projectile-completion-system 'ivy))
    :bind-keymap
    ("C-c p" . projectile-command-map)
    :init

    (when (file-directory-p "~/Works")
      (setq projectile-project-search-path '("~/Works"
                                             "~/Repositories")))
    (setq projectile-switch-project-action #'projectile-dired))

  (use-package counsel-projectile
    :config (counsel-projectile-mode))
 #+end_src

** Magit

=magit= is a git client written in =emacs-lisp= so you can easily use it inside emacs, in fact some people says that this is one of the killer feature of emacs, but I haven't found it to be true.

#+begin_src emacs-lisp
  (use-package magit
    :custom
    (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))
#+end_src

** Languange specific configuration

Each languange needs to be configured accordingly, expect LSP configuration on this section.

*** YAML

=YAML= is a human-readable data-serialization language. It is commonly used for configuration files and in applications where data is being stored or transmitted. YAML targets many of the same communications applications as Extensible Markup Language but has a minimal syntax which intentionally differs from SGML 

By default, emacs doesn't have syntax highlighting for the yaml file. So we need to install =yaml-mode= package which is hosted via melpa.

#+begin_src emacs-lisp
  (use-package yaml-mode
    :config
    (setq auto-mode-list '("\\.yml\\" . yaml-mode)))
#+end_src

*** Markdown

Markdown is a text-to-HTML conversion tool for web writers. Markdown allows you to write using an easy-to-read, easy-to-write plain text format, then convert it to structurally valid XHTML (or HTML).

It is widely used to write README document on Github, Gitlab and other Git service provider.

By default emacs doesn't have syntax highlighting for markdown file, so we need to add =markdown-mode= package inside our emacs.

#+begin_src emacs-lisp
  (use-package markdown-mode
    :ensure t
    :commands (markdown-mode gfm-mode)
    :mode (("README\\.md\\'" . gfm-mode)
           ("\\.md\\'" . markdown-mode)
           ("\\.markdown\\'" . markdown-mode))
    :init (setq markdown-command "multimarkdown"))
#+end_src

* Org Mode

Org mode is a major mode that you can activate inside a buffer, this is a killer feature of emacs, you can do literate programming using org mode and more stuff.

** Font setup

Since I probably use emacs inside its GUI client, then we can set multiple face attribute that will be rendered on the screen, this is very convenient. 

#+begin_src emacs-lisp
  (defun fain/org-font-setup ()
    ;; Replace list hyphen with dot
    (font-lock-add-keywords 'org-mode
                            '(("^ *\\([-]\\) "
                               (0 (prog1 ()
                                    (compose-region (match-beginning 1) (match-end 1) "•")
                                    ))
                               ))
                            )

    ;; Set faces for heading levels
    (dolist (face '((org-level-1 . 1.0)
                    (org-level-2 . 1.0)
                    (org-level-3 . 1.0)
                    (org-level-4 . 1.0)
                    (org-level-5 . 1.0)
                    (org-level-6 . 1.0)
                    (org-level-7 . 1.0)
                    (org-level-8 . 1.0)))

      (set-face-attribute
       (car face) nil
       :font "JetBrainsMono Nerd font:antialias=subpixel"
       :weight 'bold
       :height (cdr face)))

    ;; Ensure that anything that should be fixed-pitch in Org files appears that way
    (set-face-attribute 'org-block nil
                        :foreground nil
                        :inherit 'fixed-pitch)
    (set-face-attribute 'org-code nil
                        :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-table nil
                        :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-verbatim nil
                        :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-special-keyword nil
                        :inherit '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-meta-line nil
                        :inherit '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-checkbox nil
                        :inherit 'fixed-pitch))
#+end_src

** Setup hooks

This function is being used to setup default behaviour when we launch =org-mode=.

#+begin_src emacs-lisp
  (defun fain/org-mode-setup ()
    (org-indent-mode 1)
    (variable-pitch-mode 1)
    (visual-line-mode 1))
#+end_src

** Configuration

The =use-package= here is being used for setting up =org-mode= variables and hooks.

#+begin_src emacs-lisp
  (use-package org
    :hook (org-mode . fain/org-mode-setup)
    :config
    (setq org-ellipsis " ⤵"
          org-hide-emphasis-markers t
          org-hide-leading-stars t
          org-startup-indented t
          org-pretty-entities t
          org-fontify-whole-heading-line t
          org-fontify-done-headline t
          org-fontify-quote-and-verse-blocks t
          org-export-backends '(ascii html icalendar latex md odt gfm pdf))
    (fain/org-font-setup))
#+end_src

** Change =org-mode= Bullets

Since the default stars can be annoying let's subtitute that using =org-bullets=

#+begin_src emacs-lisp
  (use-package org-bullets
    :after org
    :hook (org-mode . org-bullets-mode)
    :custom
     (org-bullets-bullet-list '("◉")))
#+end_src

** Display text on the middle

Make =org-mode= being displayed like a true document, it has maximum width, and doesn't take up the entire screen.

#+begin_src emacs-lisp
  (defun fain/org-mode-visual-fill ()
    (setq visual-fill-column-width 100
          visual-fill-column-center-text t)
    (visual-fill-column-mode 1))

  (use-package visual-fill-column
    :hook (org-mode . fain/org-mode-visual-fill))
#+end_src

** Code block template

Org Mode’s structure templates feature enables you to quickly insert code blocks into your Org files in combination with org-tempo by typing ~<~ followed by the template name like ~el~ or ~py~ and then press ~TAB~. For example, to insert an empty emacs-lisp block below, you can type ~<el~ and press ~TAB~ to expand into such a block.

You can add more ~src~ block templates below by copying one of the lines and changing the two strings at the end, the first to be the template name and the second to contain the name of the language as it is known by [[https://orgmode.org/worg/org-contrib/babel/languages/index.html][Org Babel]].

#+begin_src emacs-lisp
  (with-eval-after-load 'org
    (require 'org-tempo)

    (add-to-list 'org-structure-template-alist '("sh" . "src shell"))
    (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
    (add-to-list 'org-structure-template-alist '("js" . "src js"))
    (add-to-list 'org-structure-template-alist '("rb" . "src ruby"))
    (add-to-list 'org-structure-template-alist '("py" . "src python")))
#+end_src

** Babel for literate programming

Org Babel is about letting many different languages work together. Programming languages live in blocks inside natural language Org documents. A piece of data might pass from an Org table to a Python code block, then maybe move on to an R code block, and finally end up embedded as a value in the middle of a paragraph or possibly pass through a Gnuplot code block and end up as a plot embedded in the document.

#+begin_src emacs-lisp
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((emacs-lisp . t)
     (python . t)
     (shell . t)))

  (push '("conf-unix" . conf-unix) org-src-lang-modes)
#+end_src

** Exports

There are bunch of packages that we can use to export org file into various formats, it is really handy not gonna lie.

*** Github Flavoured Markdown

This package is being used to export Github Flavoured Markdown, since the default markdown export sucks.

#+begin_src emacs-lisp
  (use-package ox-gfm)
#+end_src

* Keybindings

I find it emacs default keybindings sucks. So I installed some package to cater that thing.

** Make =ESC= quit prompts

 =ESC= is being used as one of our keystroke on keybindings, sometime it is registered as keystroke chain, hence we need to make it to quit the prompts.

 #+begin_src emacs-lisp
   (global-set-key (kbd "<escape>") 'keyboard-escape-quit)
 #+end_src

** Evil Mode

I love vim, and probably you also do. Emacs has a package called =evil= which will make vim available on emacs. Also, not every package that we install has =evil= keybinding, hence you need to install additional package called =evil-collection=.

#+begin_src emacs-lisp
  (use-package evil
    :init
    (setq evil-want-integration t)
    (setq evil-want-keybinding nil)
    (setq evil-want-C-u-scroll t)
    (setq evil-want-C-i-jump nil)
    :config
    (evil-mode 1)
    (define-key evil-insert-state-map (kbd "C-g") 'evil-normal-state)
    (define-key evil-insert-state-map (kbd "C-h") 'evil-delete-backward-char-and-join)

    ;; Use visual line motions even outside of visual-line-mode buffers
    (evil-global-set-key 'motion "j" 'evil-next-visual-line)
    (evil-global-set-key 'motion "k" 'evil-previous-visual-line)

    (evil-set-initial-state 'messages-buffer-mode 'normal)
    (evil-set-initial-state 'dashboard-mode 'normal))

  (use-package evil-collection
    :after evil
    :ensure t
    :pin melpa-stable
    :config (evil-collection-init))
#+end_src
